name: mbtiles_example
description: Example app for the mbtiles package
version: 1.0.0
repository: https://github.com/josxha/dart_mbtiles
issue_tracker: https://github.com/josxha/dart_mbtiles/issues

environment:
  sdk: ^3.2.0

dependencies:
  mbtiles:
  path: ^1.8.3
  path_provider: ^2.0.0

dependency_overrides:
  mbtiles:
    path: ../

dev_dependencies:
  lint: ^2.1.0