name: mbtiles_example
description: Mapbox MBTiles files using Drift for SqLite
version: 0.0.1
repository: https://github.com/josxha/dart_mbtiles
issue_tracker: https://github.com/josxha/dart_mbtiles/issues

environment:
  sdk: ^3.2.0

dependencies:
  mbtiles:
  path: ^1.8.3
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.5.18

dependency_overrides:
  mbtiles:
    path: ../

dev_dependencies:
  lint: ^2.1.0