name: On Commit
on:
  pull_request:
  push:

jobs:
  analyze-and-test:
    # sqlite3 library can't get used on linux at the moment
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Use flutter instead of just dart to run tests with coverage
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Get dependencies
        run: dart pub get
      - name: Check formatted
        run: dart format --output=none --set-exit-if-changed .
      - name: Check lints
        run: dart analyze --fatal-infos
      - name: Test
        run: flutter test --no-pub -r expanded --coverage
      - name: Test for web
        run: dart test test/mbtiles_web_test.dart --platform chrome
      - name: Run Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}